#ifndef __STORY_H__
#define __STORY_H__

//#include "common.h"
#include "script.h"
#include "gfx\stringtable.h"
#include "gfx.h"


#define none_gfx		0

#define COMMAND_ID(x) ((unsigned long)(x))
#define ENDSCENE_CLEARPAL 0
#define ENDSCENE_FADEOUT  1

#define BEGINSCENE_CMD(x) COMMAND_ID(BEGINSCENE), (unsigned long)x
#define ENDSCENE_CMD(x,y) COMMAND_ID(ENDSCENE), (unsigned long)x, (unsigned long)y
#define DIALOG_CMD(x) COMMAND_ID(DIALOG),(unsigned long)x
#define SHOWTITLE_CMD(x) COMMAND_ID(SHOWTITLE), (unsigned long)x
#define WAIT_CMD(x) COMMAND_ID(WAIT), (unsigned long)x

const unsigned long story[]={
		ENDSCENE_CMD(bg01_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(1),
		DIALOG_CMD(2),

		ENDSCENE_CMD(bg02_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),
		
		DIALOG_CMD(3),
		DIALOG_CMD(4),
		DIALOG_CMD(5),
		DIALOG_CMD(6),
		
		ENDSCENE_CMD(bg03_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),
		
		DIALOG_CMD(7),
		DIALOG_CMD(8),
		DIALOG_CMD(9),
		DIALOG_CMD(10),

		ENDSCENE_CMD(bg04_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(11),
		ENDSCENE_CMD(bg05_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(12),//  todo: shake here
		DIALOG_CMD(13),		
		DIALOG_CMD(14),

		ENDSCENE_CMD(bg06_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(15),
		DIALOG_CMD(16),
		DIALOG_CMD(17),

		ENDSCENE_CMD(bg07_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(18),
		DIALOG_CMD(19),

		ENDSCENE_CMD(bg08_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(20),

		ENDSCENE_CMD(bg09_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		DIALOG_CMD(21),
		DIALOG_CMD(22),
		DIALOG_CMD(23),
		DIALOG_CMD(24),
		DIALOG_CMD(25),
		DIALOG_CMD(26),
		DIALOG_CMD(27),

		ENDSCENE_CMD(bg10_Bitmap,ENDSCENE_FADEOUT),
		BEGINSCENE_CMD(1),

		WAIT_CMD(100),
		DIALOG_CMD(28),
		DIALOG_CMD(29),
		DIALOG_CMD(30),
		DIALOG_CMD(31),

ENDSCENE_CMD(bg19_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),


		DIALOG_CMD(32),
		DIALOG_CMD(33),
		DIALOG_CMD(34),

DIALOG_CMD(35),
DIALOG_CMD(36),
DIALOG_CMD(37),
DIALOG_CMD(38),

ENDSCENE_CMD(bg18_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),


DIALOG_CMD(39),
DIALOG_CMD(40),
DIALOG_CMD(41),

ENDSCENE_CMD(bg11_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(42),
DIALOG_CMD(43),
DIALOG_CMD(44),

ENDSCENE_CMD(bg17_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(45),
DIALOG_CMD(46),
DIALOG_CMD(47),

ENDSCENE_CMD(bg15_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),


DIALOG_CMD(48),
DIALOG_CMD(49),
DIALOG_CMD(50),
DIALOG_CMD(51),

ENDSCENE_CMD(bg16_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),


DIALOG_CMD(52),
DIALOG_CMD(53),
DIALOG_CMD(54),

ENDSCENE_CMD(bg12_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(55),
DIALOG_CMD(56),
DIALOG_CMD(57),
DIALOG_CMD(58),
DIALOG_CMD(59),
DIALOG_CMD(60),

ENDSCENE_CMD(bg13_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(61),
DIALOG_CMD(62),
DIALOG_CMD(63),
DIALOG_CMD(64),

ENDSCENE_CMD(bg14_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(65),
DIALOG_CMD(66),
ENDSCENE_CMD(bg20_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(67),

ENDSCENE_CMD(bg21_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

DIALOG_CMD(68),

ENDSCENE_CMD(bg22_Bitmap,ENDSCENE_FADEOUT),BEGINSCENE_CMD(1),

		COMMAND_ID(ENDSCRIPT)
};

#endif




















